version: 2.1

deploy-job: 
  docker: 
    - image: cimg/base:stable
  working_directory: /tmp/resume-hosting-website
  steps: 
    - run: 
      name: Deploy master to Firebase Hosting
      command: ./node_modules/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: develop