version: 2.1

jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        working_directory: ~/repo
        steps:
          - checkout
          
          - restore_cache:
              keys:
                - v1-dependencies-"{{ checksum "package.json" }}"
                - v1-dependencies-
          - run: 
                name: Install Dependencies
                command: npm install
          - save_cache:
              paths:
                - ./node_modules
              key: v1-npm-deps-{{ checksum "package.json" }}
          - run: 
                name: Build
                command: npm build
          - run:
                name: Deploy to Firebase
                command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
         